import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import adminAuthRouter from "./admin-auth";
import dashboardRouter from "./dashboard";
import transactionsRouter from "./transactions";
import balanceRouter from "./balance";
import jarsRouter from "./jars";
import goalsRouter from "./goals";
import rewardsRouter from "./rewards";
import notificationsRouter from "./notifications";
import communityRouter from "./community";
import rankingRouter from "./ranking";
import profileRouter from "./profile";
import pointsRouter from "./points";
import adminRouter from "./admin";
import solanaRouter from "./solana";
import missionsRouter from "./missions";
import transferRouter from "./transfer";
import tradeHistoryRouter from "./trade-history";
import purchaseRequestsRouter from "./purchase-requests";
import systemSettingsRouter from "./system-settings";
import searchUsersRouter from "./search-users";
import gameInviteRouter from "./game-invite";
import gachaRouter from "./gacha";
import rewardRequestsRouter from "./reward-requests";
import petStateRouter from "./pet-state";
import petCommerceRouter from "./pet-commerce";
import bugReportsRouter from "./bug-reports";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/auth", authRouter);
router.use(adminAuthRouter);
router.use(dashboardRouter);
router.use(transactionsRouter);
router.use(balanceRouter);
router.use(jarsRouter);
router.use(goalsRouter);
router.use(rewardsRouter);
router.use(notificationsRouter);
router.use(communityRouter);
router.use(rankingRouter);
router.use(profileRouter);
router.use(pointsRouter);
router.use(adminRouter);
router.use(solanaRouter);
router.use(missionsRouter);
router.use(transferRouter);
router.use(tradeHistoryRouter);
router.use(purchaseRequestsRouter);
router.use(systemSettingsRouter);
router.use(searchUsersRouter);
router.use(gameInviteRouter);
router.use(gachaRouter);
router.use(rewardRequestsRouter);
router.use(petStateRouter);
router.use(petCommerceRouter);
router.use(bugReportsRouter);

export default router;
